# Copyright (c) 2013-2015 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

language: c

# Always test Clang and GCC
compiler:
  - clang
  - gcc

# Install dependencies
before_install:

  # Upgrade autoconf to 2.69
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade autoconf

  # Install check 0.9.14
  - wget http://downloads.sourceforge.net/check/check-0.9.14.tar.gz
  - tar -xvf check-0.9.14.tar.gz
  - cd check-0.9.14 && ./configure --prefix=/usr && make && sudo make install
  - cd ..

  # Install lcov 1.11
  - wget http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz
  - tar -xvf lcov-1.11.tar.gz
  - cd lcov-1.11 && sudo make install
  - cd ..

  # Install protobuf 2.6.1
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xvf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1 && ./configure --prefix=/usr && make && sudo make install
  - cd ..

  # Install coveralls integration
  - gem install coveralls-lcov

  # Generate build environment
  - ./autogen.sh

# Perform build and tests
script: ./configure --enable-coverage && make && make test

# If successful, create and push coverage report
after_success:
  - cd tools/coverage && make
  - coveralls-lcov coverage.info